#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_service_delete:
    path: /service/delete/{id}
    controller: App\Controller\ServiceController::delete

currency_ticker:
    path: /currency-ticker
    controller: App\Controller\CurrencyController::index
