#index:
#    path: /
#    controller: App\Controller\DefaultController::index
search_demande_achat:
  path: /demande_achat/search
  controller: App\Controller\DemandeAchatController::search
  methods: GET
gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_gcb