#index:
#    path: /
#    controller: App\Controller\DefaultController::index
search_demande_achat:
  path: /demande_achat/search
  controller: App\Controller\DemandeAchatController::search
  methods: GET
app_reponse_conge_show:
    path: '/reponse/conge/{id}'
    controller: 'App\Controller\ReponseCongeController::show'
    methods: ['GET']
    requirements:
        id: '\d+'